### ISSUE TITLE
想钱想疯了吧，key都有人公开了

### ISSUE THREAD

**Issue by icesunx** [HackAppSign/douyin-sign#1]
https://github.com/8600/douyin-sign/blob/master/douyin.py

**Comment by liebian** [comment]
好厉害哟~~老版本的已放开

新版本的大佬你自己来

**Comment by icesunx** [comment]
大佬这名号担不起，我就想知道大神你们搞定点赞了没有@liebian

**Comment by liebian** [comment]
@icesunx  谦虚了~新版IDA动态调试中~~(就窝一个人)

不过点赞的话~~规模没起来是亏的啊， 比如 http://liebian.12mx.cn 这种规模化搞的成本压得很低了

PS: 对于在老版本隐藏token的行为~~郑重向大佬道歉(隐藏token只是想加个好友了解一下需求, github上kanxue上一大堆老版本的代码, 都能给找出来吧)
